version: '3.8'

networks:
  data-exchange:
    driver: bridge
    name: data-exchange

services:
  minio:
    image: minio/minio
    container_name: minio-storage
    networks:
      - data-exchange
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - data-exchange
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 admin password) do echo 'Waiting for MinIO...' && sleep 2; done;
      /usr/bin/mc mb local/lakehouse;
      exit 0;
      "
